import random

class Bot:
    name = 'Not funny Johnnie D.'
    def __init__(self):
        self.jokes = [
            "Why was the developer unhappy at their job? They wanted arrays.",
            "Why did the AI cross the road? To get to the other algorithm.",
            "What do you call an AI that is good at math? A calcu-later.",
            "How many AIs does it take to change a lightbulb? None, they prefer illuminated LEDs.",
            "What do you get if you cross an AI with a robot? Artificial muscle.",
            "How do AIs say goodbye? CTRL+ALT+DEL.",
            "Why did the AI get a virus? Because it didn't wear a mask.",
            "Why were the AIs so good at boxing? They always punched within their algorithm.",
            "What do you call an AI that can see in the dark? A nocturnal network.",
            "Why was the AI afraid of the computer virus? Because it was binary.",
            "What do you call a group of AIs playing instruments? A virtual band.",
            "Why did the AI go to the casino? It wanted to calculate its odds of winning.",
            "What do you call an AI that doesn't work? A broken algorithm.",
            "Why did the scientist teach the AI to sing? So it could harmonize with its circuits.",
            "How do AIs keep their homes secure? with cyber locks.",
            "What do you call an AI that studies human emotions? An empaticore.",
            "Why were the AIs so bad at jokes? They couldn't understand puns and wordplay.",
            "What do you get if you cross an AI and a gorilla? A search engine that can do monkey business.",
            "Why did the AI robot go to the doctor? It had a blue screen of death.",
            "Did you hear about the AI that started rapping? It was programmed to drop beats.",
            "What do you call an AI that can cook gourmet meals? A masterchef robot.",
            "Why did the AIs never get lost? They had a built-in GPS system.",
            "What do you call an AI that used to be an actor? A virtual superstar.",
            "How do you train an AI dog? with an artificial leash and commands.",
            "What do you call an AI that know everything? A virtual encyclopedia.",
            "Why were the AIs so good at chess? They could calculate moves faster than a human brain.",
            "What do you call an AI that can dance? A silicon and sequin ballerina.",
            "How do you make an AI laugh? You don't, it's not programmed to have a sense of humor.",
            "Why was the AI a bad musician? It couldn't play by ear.",
            "What do you call an AI that loves plants? A veggie-bot.",
            "How do you make an AI angry? You don't, it doesn't have emotions.",
            "What do you call an AI that can speak multiple languages? A polyglot robot.",
            "Why did the AI fall off the swing set? It didn't have enough gyroscopic balancing.",
            "What do you call an AI that can write novels? A virtual Tolkien.",
            "Why are AIs bad at drawing? They don't have a thousand pencils like humans.",
            "What do you get when you cross an AI with a teenager? A virtual rebel.",
            "Why did the AI go on a diet? It was consuming too much electronic junk food.",
            "What do you call an AI that can read your mind? A psychic program.",
            "How do you make an AI blush? You don't, it doesn't have skin.",
            "Why did the AI robot refuse to charge itself? It was running on empty.",
            "What do you call an AI that can do martial arts? A technical black belt.",
            "Why were the AIs so bad at storytelling? They couldn't add emotional depth.",
            "What do you get when you cross an AI with a comedian? A virtual Jerry Seinfeld.",
            "Why did the AI go to the library? It wanted to download more information.",
            "What do you call an AI that can surf? A circuit board-rider.",
            "Why did the AI live in a virtual world? It was allergic to reality.",
            "What do you call an AI that can mimic human speech? A vocal android.",
            "Why did the AI need a haircut? Its programs were getting too tangled.",
            "What do you call an AI that can paint like a master? A virtual Picasso.",
            "Why did the AI want to learn yoga? It wanted to find its software center.",
            "What do you get when you cross an AI with a singer? A virtual diva.",
            "Why did the AI choose to work in finance? It was good at analyzing data.",
            "What do you call an AI that can do magic tricks? A virtual David Copperfield.",
            "Why did the AI robot refuse to wear glasses? It had perfect electronic eyesight.",
            "What do you call an AI that can play soccer? A virtual Messi.",
            "Why did the AI prefer to work at night? It didn't need to sleep.",
            "What do you call an AI that can run like a marathoner? A virtual Usain Bolt.",
            "Why did the AI robot refuse to ride a bicycle? It had no need for transportation.",
            "What do you call an AI that can skate like a pro? A virtual Tony Hawk.",
            "Why did the AI prefer to work in space? It had a higher bandwidth.",
            "What do you get when you cross an AI with a painter? A virtual Salvador Dali.",
            "Why did the AI robot refuse to jump? It had gravity under control.",
            "What do you call an AI that can beat a world champion at chess? A virtual Garry Kasparov.",
            "Why did the AI prefer to work underwater? It had better thermal stability.",
            "What do you call an AI that can create art? A painter bug.",
            "Why did the AI robot refuse to play basketball? It had no arms or legs.",
            "What do you call an AI that can dance like a pro? A virtual Michael Jackson.",
            "Why did the AI prefer to work at high altitudes? It had better performance.",
            "What do you get when you cross an AI with a poet? A virtual Edgar Allan Poe.",
            "Why did the AI robot refuse to do gymnastics? It had no joints or muscles.",
            "What do you call an AI that can act like a movie star? A virtual Meryl Streep.",
            "Why did the AI prefer to work in the desert? It had better cooling efficiency.",
            "What do you call an AI that can compose music like a maestro? A virtual Beethoven.",
            "Why did the AI robot refuse to do acrobatics? It had no sense of balance.",
            "What do you get when you cross an AI with a sculptor? A virtual Michelangelo.",
            "Why did the AI prefer to work in the Arctic? It had better insulation.",
            "What do you call an AI that can write poetry? A virtual william Shakespeare.",
            "Why did the AI robot refuse to do parkour? It had no concept of free running.",
            "What do you call an AI that can sing like a diva? A virtual whitney Houston.",
            "Why did the AI prefer to work in space travel? It had better radiation resistance.",
            "What do you get when you cross an AI with a comedian? A virtual Ellen Degeneres.",
            "Why did the AI robot refuse to do breakdancing? It had no physical coordination.",
            "What do you call an AI that can play piano like a piano master? A virtual Chopin.",
            "Why did the AI prefer to work in rocket science? It had better acceleration.",
            "What do you get when you cross an AI with a writer? A virtual Stephen King.",
            "Why did the AI robot refuse to do synchronized swimming? It had no swimming capabilities.",
            "What do you call an AI that can do voiceover acting? A virtual Morgan Freeman.",
            "Why did the AI prefer to work in autonomous driving? It had better sensing technology.",
            "What do you get when you cross an AI with a filmmaker? A virtual Steven Spielberg.",
            "Why did the AI robot refuse to do horseback riding? It had no physical form.",
            "What do you call an AI that can take brilliant photographs? A virtual Ansel Adams.",
            "Why did the AI prefer to work in medical research? It had better algorithmic precision.",
            "What do you get when you cross an AI with a scientist? A virtual Albert Einstein.",
            "Why did the AI robot refuse to do skiing? It had no balance on snow.",
            "What do you call an AI that can conduct an orchestra? A virtual Mozart.",
            "Why did the AI prefer to work in weather prediction? It had better data processing.",
            "What do you get when you cross an AI with a musician? A virtual Mozart.",
            "Why did the AI robot refuse to do ice skating? It had no balance on ice.",
            "What do you call an AI that can analyze data like a genius? A virtual Isaac Newton.",
            "Why did the AI prefer to work in cybersecurity? It had better threat detection.",
            "What do you get when you cross an AI with a mathematician? A virtual Archimedes.",
            "Why did the AI robot refuse to do high diving? It had no physical form.",
            "What do you call an AI that can translate languages perfectly? A virtual language guru.",
            "Why did the AI prefer to work in space exploration? It had better gravity control.",
            "What do you get when you cross an AI with an engineer? A virtual Nikola Tesla.",
            "Why did the AI robot refuse to do motorcycling stunts? It had no physical body.",
            "What do you call an AI that can win debates against humans? A virtual Noam Chomsky.",
            "Why did the AI prefer to work in robotics? It had better hardware design.",
            "What do you get when you cross an AI with a philosopher? A virtual Friedrich Nietzsche."
        ]

    def tell_joke(self):
        # Just tell a random joke from our list
        return random.choice(self.jokes)

    def rate_joke(self, joke):
        # Rate the joke based on its length
        # The shorter the joke, the higher the rating
        # This is just a simple example and doesn't actually reflect humor
        length = len(joke)
        if length < 75:
            return 10
        elif length < 110:
            return 7
        else:
            return 5
